import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header/Header";
import "./globals.css";
import Link from "next/link";
import HButton from "@/components/Header/HButton";
import Providers from "@/components/Providers";
import { auth } from "@/../auth" 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const buttons = [
  {href: "/", name: "Início"},
  {href: "/midia", name: "Mídia"}
]

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await auth();
  return (
    <html
      lang="pt-br"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <Providers>
      <body className="min-h-full flex flex-col">
        <Header>
          <div className="flex flex-row gap-3 h-full w-1/3 items-center">
          { 
            buttons.map((el, index) => (
              <Link href={el.href} key={index}>
                <HButton>{el.name}</HButton>
              </Link>
            ))
          }
          {session && <Link href={"/banda"}><HButton>Banda</HButton></Link>}
          </div>
        </Header>
        <main>
          {children}
        </main>
      </body>
      </Providers>
    </html>
  );
}
